import type { LucideIcon } from 'lucide-react-native';
import {
  AlertCircle,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Check,
  Copy,
  CreditCard,
  Home,
  History,
  Info,
  Lock,
  Plus,
  Search,
  Settings,
  Slash,
  Star,
  Trash2,
  User,
  Users,
  X,
} from 'lucide-react-native';

export const iconsMap = {
  alertCircle: AlertCircle,
  calendar: Calendar,
  check: Check,
  copy: Copy,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  creditCard: CreditCard,
  home: Home,
  history: History,
  info: Info,
  lock: Lock,
  plus: Plus,
  search: Search,
  settings: Settings,
  slash: Slash,
  star: Star,
  trash: Trash2,
  user: User,
  users: Users,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof iconsMap;
