<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>34591fa2-d049-4205-8992-fb023063ef79</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2" />
	</ItemGroup>

</Project>
